// <auto-generated />
namespace AutoFocus_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class r4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(r4));
        
        string IMigrationMetadata.Id
        {
            get { return "201910211127474_r4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
