// <auto-generated />
namespace AutoFocus_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedondeletecascadefromcustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedondeletecascadefromcustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "201910210820021_Added on delete cascade from customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
